AppGema/urls.py
from django.urls import path
from AppGema.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    
    #URL de inicio y about me 
    path ("", inicio, name = "Inicio"),
    path("about", about_me, name = "Acerca de mi"),
    
    #URLS de registro
    path("login/", inicio_sesion, name="Login"),
    path("register/", registro, name="SignUp"),
    path("logout/", cerrar_sesion, name = "Cerrar_sesion"),
    path("edit/", editar_perfil, name= "Editar usuario"),
    path("contra/", Cambiar_Contra.as_view(), name = "Cambiar Contraseña"),
    
    #URL de avatar
    path("avatar/", agregar_avatar, name= "Agregar Avatar"),
    
    #CRUD de reservas
    
    path("leer_reservas/", leer_reservas, name="Reservas_leer"),
    path("crear_reservas/", crear_reservas, name="Reservas_crear"),
    path("eliminar_reservas/<name>/", eliminar_reservas, name = "Reservas_eliminar"),
    path("editar_reservas/<name>/", editar_reservas, name = "Reservas_editar"),
    
    #CRUD de huesped 
    
    path("huesped/list",Lista_Huesped.as_view(), name= "Huespedes_Leer"),
    path("huesped/<int:pk>",Detalle_Huesped.as_view(), name= "Huespedes_Detalle"),
    path("huesped/crear/",Crear_Huesped.as_view(), name= "Huespedes_Crear"),
    path("huesped/editar/<int:pk>",Actualizar_Huesped.as_view(), name= "Huespedes_Editar"),
    path("huesped/borrar/<int:pk>", Borrar_Huesped.as_view(), name= "Huespedes_Borrar"),
    
    #CRUD de habitacion 
    
    path("habitacion/list",Lista_Habitacion.as_view(), name= "Habitaciones_Leer"),
    path("habitacion/<int:pk>",Detalle_Habitacion.as_view(), name= "Habitaciones_Detalle"),
    path("habitacion/crear/",Crear_Habitacion.as_view(), name= "Habitaciones_Crear"),
    path("habitacion/editar/<int:pk>",Actualizar_Habitacion.as_view(), name= "Habitaciones_Editar"),
    path("habitacion/borrar/<int:pk>", Borrar_Habitacion.as_view(), name= "Habitaciones_Borrar"),
    
]

HotelGema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppGema/',include('AppGema.urls') )
]

urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppGema/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Habitacion (models.Model):
    
    nombre = models.CharField(max_length = 60)
    camas = models.IntegerField()
    
    def __str__ (self):
        
        return f"habitacion tipo {self.nombre} ------- contiene {self.camas} cama/s"

class Huesped (models.Model):
    
    nombre = models.CharField(max_length = 60)
    apellido = models.CharField(max_length = 60)
    correo = models.EmailField()
    
    def __str__(self):
        
        return f"{self.nombre} --- {self.apellido}."
    
class Reserva (models.Model):
    
    nombre = models.CharField(max_length = 60,null= True, blank= True, default = None)
    apellido = models.CharField(max_length = 60,null= True, blank= True, default= None)
    checkin = models.DateField()
    checkout = models.DateField()
    
    
    
    def __str__(self):
        
        return f"reserva a nombre de {self.nombre} con ingreso el  {self.checkin}"
    
    
class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to= "avatares", null= True, blank=True)
    
    def __str__(self):
        
        return f"{self.usuario} --- {self.imagen}"

AppGema/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class HuespedFormulario (forms.Form):
    nombre = forms.CharField()
    apellido = forms.CharField()
    correo = forms.EmailField()
    
class ReservaFormulario (forms.Form):
    nombre = forms.CharField()
    apellido = forms.CharField()
    checkin = forms.DateField()
    checkout = forms.DateField()

class AvatarFormulario(forms.Form):
    imagen =forms.ImageField()      

class UsuarioRegistro (UserCreationForm):
    
    email = forms.EmailField()
    password1 = forms.CharField(label = "contraseña", widget = forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir la contraseña", widget = forms.PasswordInput)
    
    class Meta:
        
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2" ]
        



class EditarUsuario (UserChangeForm):

    password = None
    
    class Meta:
        
        model = User
        fields = ["email", "first_name", "last_name" ]
        
        
  

AppGema/views.py
from django.shortcuts import render
from AppGema.models import Habitacion
from AppGema.forms import *
from AppGema.models import Huesped, Reserva, Avatar
from django.views.generic import  ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.views import PasswordChangeView

# Create your views here.

#Vista de inicio y about me

def inicio (request):
    
    return render(request, "AppGema/inicio.html")

def about_me (request):
    
    return render (request, "AppGema/about.html")


# Vistas de registro/login/logout

def registro (request):
    
    if request.method =="POST":
        
        form = UsuarioRegistro(request.POST)
        
        if form.is_valid():
            
            username = form.cleaned_data["username"]
            form.save()
            return render (request,"AppGema/inicio.html", {"mensaje": "Usuario creado"})
        
    else:
        
        form = UsuarioRegistro()
        
    return render(request, "AppGema/registro/registro.html", {"formulario":form})    



def inicio_sesion (request):
    
    if request.method =="POST":
        
        form = AuthenticationForm(request, data = request.POST)
        
        if form.is_valid():
            
            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")
            
            user = authenticate(username=usuario, password = contra)
            
            if user:
                
                login(request, user)
                
                return render(request, "AppGema/inicio.html", {"mensaje":f"Bienvenido  {user}"})
            
        else:
            
            return render(request, "AppGema/inicio.html", {"mensaje": "Datos incorrectos."})    

    else:
                
        form  = AuthenticationForm()    

    return render(request, "AppGema/registro/login.html", {"formulario": form})


def cerrar_sesion(request):
    
    logout(request)
    
    return render(request, "AppGema/inicio.html", {"mensaje": "Hasta pronto!"})


# Vista de editar el perfil

@login_required
def editar_perfil(request):

    usuario = request.user

    if request.method == 'POST':

        miFormulario = EditarUsuario(request.POST)

        if miFormulario.is_valid():

            informacion = miFormulario.cleaned_data

            usuario.email = informacion['email']
            usuario.last_name = informacion['last_name']
            usuario.first_name = informacion['first_name']

            usuario.save()

            return render(request, "AppGema/inicio.html")

    else:

        miFormulario = EditarUsuario(initial={'first_name': usuario.first_name,
                                             'last_name':usuario.last_name, 'email': usuario.email})

    return render(request, "AppGema/editar_usuario.html", {"formulario": miFormulario})


# Cambiar contraseña    
    
class Cambiar_Contra(LoginRequiredMixin, PasswordChangeView):
    template_name = "AppGema/cambiar_contra.html"
    success_url = "/AppGema/"

    
#Vista de agregar avatar

@login_required
def agregar_avatar (request):
    
    if request.method =="POST":
        
        form = AvatarFormulario(request.POST, request.FILES)
        
        
        if form.is_valid():
            
            info = form.cleaned_data
            
            usuario_actual= User.objects.get(username=request.user)
            nuevo_avatar = Avatar (usuario= usuario_actual, imagen=info["imagen"])
            
            nuevo_avatar.save()
            
            return render (request,"AppGema/Inicio.html", {"mensaje": "Has creado tu avatar"})
        
    else:
        
        form = AvatarFormulario()
        
    return render(request, "AppGema/nuevo_avatar.html", {"formulario":form})            




#Vistas de Reservas (basadas en funciones)

@login_required
def reserva (request):
    
    return render(request, "AppGema/reserva.html")



@login_required
def leer_reservas(request):
    
    reservas = Reserva.objects.all()
    
    contexto = {"reservations":reservas}
    
    return render(request,"AppGema/reservas/leer_reservas.html", contexto)

@login_required
def crear_reservas(request):
    
    if request.method == "POST":
        
        miFormulario = ReservaFormulario(request.POST)
        
        if miFormulario.is_valid():
            
            info = miFormulario.cleaned_data
            
            reserva = Reserva(nombre = info["nombre"],
                              apellido = info["apellido"],
                              checkin = info["checkin"],
                              checkout = info["checkout"]
                              
                              )
                              
            
            reserva.save()
            
            return render(request, "AppGema/inicio.html")
    else:
        miFormulario = ReservaFormulario() 
    
    return render(request, "AppGema/reservas/reservaformulario.html", {"miFormulario": miFormulario})

@login_required
def eliminar_reservas(request, name):
    
    reserva = Reserva.objects.get(nombre =name)
    reserva.delete()
    
    reservas = Reserva.objects.all()
    
    contexto = {"reservations": reservas}
    
    return render (request, "AppGema/reservas/leer_reservas.html", contexto)

@login_required
def editar_reservas(request, name):
    reserva = Reserva.objects.get(nombre = name)
    
    if request.method == "POST":
        
        miFormulario = ReservaFormulario(request.POST)
        
        if miFormulario.is_valid():
            
            info = miFormulario.cleaned_data
            reserva.nombre = info["nombre"],
            reserva.apellido = info["apellido"],
            reserva.checkin = info["checkin"]
            reserva.checkout = info["checkout"]
                              
            reserva.save()
            
            return render(request, "AppGema/inicio.html")
    else:
        miFormulario = ReservaFormulario(initial={"nombre": reserva.nombre, "apellido": reserva.apellido}) 
    
    return render(request, "AppGema/reservas/editar_reservas.html", {"miFormulario": miFormulario, "nombre": name})

# Vistas de Huesped (basadas en clases)
            
class Lista_Huesped(LoginRequiredMixin,ListView):
    template_name = "AppGema/huespedes/huesped_list.html"
    model = Huesped
    
class Detalle_Huesped(LoginRequiredMixin, DetailView):
    
    template_name = "AppGema/huespedes/huesped_detail.html"
    model = Huesped
    
class Crear_Huesped(LoginRequiredMixin, CreateView):
    
    model = Huesped
    template_name = "AppGema/huespedes/huesped_form.html"
    success_url = "/AppGema/huesped/list"
    fields = ["nombre","apellido","correo"]
    
class Actualizar_Huesped (LoginRequiredMixin, UpdateView):
    
    model = Huesped
    template_name = "AppGema/huespedes/huesped_form.html"
    success_url = "/AppGema/huesped/list"
    fields = ["nombre","apellido","correo"]
    
class Borrar_Huesped(LoginRequiredMixin, DeleteView):
    
    model = Huesped
    template_name = "AppGema/huespedes/huesped_confirm_delete.html"
    success_url = "/AppGema/huesped/list"

# Vistas de habitacion (basadas en clases)

class Lista_Habitacion(ListView):
    
    model = Habitacion
    template_name = "AppGema/habitaciones/habitacion_list.html"
    
class Detalle_Habitacion(DetailView):
    
    model = Habitacion
    template_name = "AppGema/habitaciones/habitacion_detail.html"
    
class Crear_Habitacion(LoginRequiredMixin, CreateView):
    
    model = Habitacion
    template_name = "AppGema/habitaciones/habitacion_form.html"
    success_url = "/AppGema/habitacion/list"
    fields = ["nombre","camas",]
    
class Actualizar_Habitacion (LoginRequiredMixin, UpdateView):
    
    model = Habitacion
    template_name = "AppGema/habitaciones/habitacion_form.html"
    success_url = "/AppGema/habitacion/list"
    fields = ["nombre","camas"]
    
class Borrar_Habitacion(LoginRequiredMixin, DeleteView):
    
    model = Habitacion
    template_name = "AppGema/habitaciones/habitacion_confirm_delete.html"
    success_url = "/AppGema/habitacion/list"
    

    

        


    


AppGema/templates/AppGema/about.html
{% extends "AppGema/padre.html" %}


{% load static %}


{% block titulo %}

Acerca de mi

{% endblock %}





{% block descripcion %}

<p>Mi nombre es Facundo soy de Montevideo Uruguay, trabajo en un hotel y es mi primer experiencia en programacion espero les
     guste mi pagina. Saludos!
</p>

{% endblock %}

AppGema/templates/AppGema/cambiar_contra.html
{% extends "AppGema/padre.html" %}


{% load static %}





{% block descripcion %}

<form action=""method="POST">{% csrf_token %}


    {{form.as_p}}
    
    <button type="submit"> cambiar contraseña </button></button>

    {% endblock %}

AppGema/templates/AppGema/editar_usuario.html
{% extends "AppGema/padre.html" %}


{% load static %}








{% block descripcion %}

<form action=""method="POST">{% csrf_token %}


    {{formulario.as_p}}

    <button type="submit"> Editar </button></button>

    {% endblock %}

AppGema/templates/AppGema/inicio.html
{% extends "AppGema/padre.html" %}


{% load static %}


{% block titulo %}

{{mensaje}}

{% endblock %}





{% block descripcion %}

<div class="d-flex justify-content-center">
    <div class="text-center">
        
        <h2 class="text-white-50 mx-auto mt-2 mb-5">Comienze a planear sus vacaciones lejos de las preocupaciones.</h2>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'Reservas_crear' %}">Reservar ahora</a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'Login' %}">Log in</a>
        {% endif %}
    </div>
</div>

{% endblock %}

AppGema/templates/AppGema/nuevo_avatar.html
{% extends "AppGema/padre.html" %}


{% load static %}






{% block descripcion %}

<form action=""method="POST" enctype="multipart/form-data">{% csrf_token %}


    {{formulario.as_p}}

    <button type="submit">Avatar creado</button></button>




</form>

{% endblock %}

AppGema/templates/AppGema/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Hotel Gema</title>
        <link rel="icon" type="image/x-icon" href="{% static 'AppGema/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppGema/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                {% if not user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'SignUp' %}">SignUp</a>
                {% else %}
                <a class="navbar-brand" href="{% url 'Inicio' %}">Home</a>
                {% endif %}
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'Reservas_leer' %}">Reservas</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Habitaciones_Leer' %}">Rooms</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Huespedes_Leer' %}">Guest</a></li>
                           {% if user.is_authenticated %}
                        <li><a href="{% url 'Editar usuario' %}">{{user.first_name}}</a></li>
                        {% if user.avatar_set.last %}
                        <li><img src="{{user.avatar_set.last.imagen.url}}" width="50px" height="30px" alt="Foto usuario"></li>
                        {% else %}
                        <li><img src="{% static 'AppGema/assets/img/avatar-defecto.jpg' %}"width="50" height="30px"alt=""></li>
                        {% endif %}
                        <li><a href="{% url 'Agregar Avatar' %}">Cambiar avatar</a></li>
                        <li><a href="{% url 'Cambiar Contraseña' %}">Cambiar contra</a></li>   
                        <li class="nav-item"><a class="nav-link" href="{% url 'Cerrar_sesion' %}">Cerrar sesion</a></li>
                            {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase">

                            {% block titulo %}

                                

                            {% endblock %}

                        </h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">

                            {% block descripcion %}
                            {% endblock %}



                        </h2>
                        

                        


                        </a>
                    </div>
                </div>
            </div>
        </header>
       
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                    <a class="nav-link- about-me-link" href="{% url 'Acerca de mi' %}">About me</a>
                        <p class="text-white-50">